from backend.models import Playlist, Video, HistoryRun, HistoryPlaylist, LogEntry

SAMPLE_VIDEOS: list[Video] = [
    Video(title="Master Your Sleep & Be More Alert When Awake", duration_sec=7234, stage="done"),
    Video(title="Using Science to Optimize Sleep, Learning & Metabolism", duration_sec=6512, stage="done"),
    Video(title="Find Your Temperament Type & Optimize Your Life", duration_sec=4980, stage="failed",
          failed_at="download", error="HTTP 410 — video unavailable in your region", retry_count=2),
    Video(title="Adderall, Stimulants & Modafinil for ADHD: Short- & Long-Term Effects", duration_sec=10422,
          stage="speed", progress=0.62),
    Video(title="Maximizing Productivity, Physical & Mental Health with Daily Tools", duration_sec=8755,
          stage="mp3", progress=0.31),
    Video(title="Tools for Managing Stress & Anxiety", duration_sec=6201, stage="failed",
          failed_at="mp3", error="ffmpeg exited 1 — codec_open2 failed", retry_count=0),
    Video(title="How to Focus to Change Your Brain", duration_sec=5012, stage="queued"),
    Video(title="How Smell, Taste & Pheromone-Like Chemicals Control You", duration_sec=7700, stage="queued"),
]

MOCK_PLAYLISTS: list[Playlist] = [
    Playlist(
        id="pl0", prefix="00",
        title="Andrew Huberman — Sleep Toolkit",
        url="https://youtube.com/playlist?list=PLoOpuURvl_ON8k-iKjD6kOAp9-eWPY2bq",
        video_count=12, completed=12,
        status="done", active_stage="done",
        speed=1.75, split_enabled=True, split_min=30,
        size_mb=412.8, added_at="May 24, 9:14",
        videos=list(SAMPLE_VIDEOS),
    ),
    Playlist(
        id="pl1", prefix="01",
        title="Lex Fridman — AI Researchers (2024)",
        url="https://youtube.com/playlist?list=PLrAXtmRdnEQy6nuLMfO6F4F0lq3v8u3XS",
        video_count=24, completed=11,
        status="active", active_stage="speed",
        speed=1.5, split_enabled=True, split_min=45,
        size_mb=218.4, added_at="May 26, 11:02",
        videos=list(SAMPLE_VIDEOS),
    ),
    Playlist(
        id="pl2", prefix="02",
        title="Naval Ravikant — The Almanack",
        url="https://youtube.com/playlist?list=PLpVNXY2_z3pBh7w7tH0FbHBzZxRD9Nq28",
        video_count=7, completed=0,
        status="queued", active_stage="download",
        speed=2.0, split_enabled=False, split_min=30,
        size_mb=None, added_at="May 27, 0:09",
        videos=[Video(title=f"Video {i+1}", duration_sec=0, stage="queued") for i in range(7)],
    ),
    Playlist(
        id="pl3", prefix="03",
        title="Chess Speedrun — Hikaru Nakamura",
        url="https://youtube.com/playlist?list=PLtcw3vJsi3M8c9KEEyNXIxoZjeqr1V6q",
        video_count=18, completed=0,
        status="queued", active_stage="download",
        speed=1.25, split_enabled=False, split_min=30,
        size_mb=None, added_at="May 27, 0:11",
        videos=[Video(title=f"Video {i+1}", duration_sec=0, stage="queued") for i in range(18)],
    ),
]

MOCK_HISTORY: list[HistoryRun] = [
    HistoryRun(
        id="run-047", num=47,
        started_at="May 24, 2026 · 09:14", duration_min=38,
        playlist_count=12, video_count=142, size_mb=1842.6,
        output_path="D:\\Audio\\Anees\\run-2026-05-24",
        merged=True, merged_path="D:\\Audio\\Anees\\_merged",
        status="success",
        playlists=[
            HistoryPlaylist("00", "Andrew Huberman — Sleep Toolkit", 12, 412.8, 1.75),
            HistoryPlaylist("01", "Tim Ferriss — Tools of Titans interviews", 18, 580.2, 1.5),
            HistoryPlaylist("02", "Naval Ravikant — The Almanack", 7, 142.1, 2.0),
            HistoryPlaylist("03", "Cal Newport — Deep Work talks", 9, 233.7, 1.5),
        ],
    ),
    HistoryRun(
        id="run-046", num=46,
        started_at="May 21, 2026 · 22:08", duration_min=22,
        playlist_count=6, video_count=64, size_mb=884.3,
        output_path="D:\\Audio\\Anees\\run-2026-05-21",
        merged=True, merged_path="D:\\Audio\\Anees\\_merged",
        status="success",
        playlists=[
            HistoryPlaylist("00", "Sam Harris — Making Sense ep. 350-360", 11, 288.4, 1.75),
            HistoryPlaylist("01", "Lex Fridman — AI Researchers (2024)", 24, 412.0, 1.5),
        ],
    ),
    HistoryRun(
        id="run-045", num=45,
        started_at="May 19, 2026 · 18:42", duration_min=14,
        playlist_count=4, video_count=32, size_mb=412.0,
        output_path="D:\\Audio\\Anees\\run-2026-05-19",
        merged=False, merged_path=None,
        status="partial",
        playlists=[
            HistoryPlaylist("00", "Andrej Karpathy — Neural Networks: Zero to Hero", 10, 181.2, 1.5),
            HistoryPlaylist("01", "3Blue1Brown — Essence of Linear Algebra", 15, 118.4, 1.5),
        ],
    ),
    HistoryRun(
        id="run-044", num=44,
        started_at="May 17, 2026 · 11:30", duration_min=51,
        playlist_count=15, video_count=188, size_mb=2188.0,
        output_path="D:\\Audio\\Anees\\run-2026-05-17",
        merged=True, merged_path="D:\\Audio\\Anees\\_merged",
        status="success",
        playlists=[
            HistoryPlaylist("00", "Stratechery interviews", 14, 421.0, 1.5),
            HistoryPlaylist("01", "Acquired — full episodes", 8, 610.0, 1.75),
            HistoryPlaylist("02", "EconTalk — Russ Roberts", 22, 740.0, 1.5),
        ],
    ),
]

MOCK_LOGS: list[LogEntry] = [
    LogEntry("09:14:02.118", "info",  "app",    "Run #048 started — 4 playlists in queue, 2 parallel workers"),
    LogEntry("09:14:02.247", "info",  "app",    "Output root: D:\\Audio\\Anees\\run-2026-05-27"),
    LogEntry("09:14:02.881", "info",  "yt-dlp", "[youtube:tab] Extracting URL: youtube.com/playlist?list=PLoOpuURvl_ON8k-iKjD6kOAp9-eWPY2bq"),
    LogEntry("09:14:03.604", "info",  "yt-dlp", "[youtube:tab] PLoOpuURvl_ON8k: Downloading playlist (12 videos)"),
    LogEntry("09:14:05.122", "info",  "yt-dlp", "[01/12] Master Your Sleep — downloading ⇒ extracting audio"),
    LogEntry("09:14:48.012", "info",  "ffmpeg", "Mono conversion: input=44100Hz stereo → 22050Hz mono, libmp3lame VBR -q:a 2"),
    LogEntry("09:15:11.339", "info",  "ffmpeg", "Speed-up atempo=1.75 applied (output 4136s)"),
    LogEntry("09:15:11.401", "info",  "app",    "00_01_Master Your Sleep.mp3 saved (39.2 MB)"),
    LogEntry("09:18:44.207", "info",  "yt-dlp", "[02/12] Using Science to Optimize Sleep ⇒ processed (47.1 MB)"),
    LogEntry("09:21:02.118", "warn",  "yt-dlp", "[03/12] Retry 1/3 after HTTP 503 backoff 2s"),
    LogEntry("09:21:04.661", "warn",  "yt-dlp", "[03/12] Retry 2/3 after HTTP 503 backoff 4s"),
    LogEntry("09:21:08.882", "error", "yt-dlp", "[03/12] Find Your Temperament Type — failed",
             detail="HTTP Error 410: Gone\nVideo unavailable in your country.\n  at YoutubeDL.process_video(yt_dlp/YoutubeDL.py:3411)\n  at YoutubeDL.download(yt_dlp/YoutubeDL.py:3502)",
             code="YT_DLP_HTTP_410"),
    LogEntry("09:21:09.001", "info",  "app",    "[03/12] Marked failed, continuing to next video"),
    LogEntry("09:24:30.110", "info",  "yt-dlp", "[04/12] Adderall, Stimulants & Modafinil — downloading"),
    LogEntry("09:28:11.402", "info",  "ffmpeg", "[04/12] atempo=1.75 in progress (62%)"),
    LogEntry("09:29:55.001", "debug", "ffmpeg", "frame=12440 fps=2400 q=4.0 size=8192kB time=00:06:42 bitrate=167.2kbits/s speed=77.8x"),
    LogEntry("09:33:14.901", "error", "ffmpeg", "[06/12] ffmpeg exited with code 1",
             detail="[mp3float @ 0x55a6e8] Header missing\n[mp3float @ 0x55a6e8] codec_open2 failed for stream #0\nError while decoding stream #0:0: Invalid data found when processing input\nConversion failed!",
             code="FFMPEG_CODEC_OPEN2"),
    LogEntry("09:35:44.001", "warn",  "app",    "Disk usage 92% on D:\\ — 1.4 GB free"),
    LogEntry("09:38:02.001", "info",  "app",    "Playlist 01 complete: 10/12 success, 2 failed"),
    LogEntry("09:38:02.224", "info",  "app",    "Starting playlist 02 — Lex Fridman"),
]
